# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  # adapter: sqlite3
  # adapter: mysql
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_todo
  password: 'todo'


development:
  <<: *default
  database: todo_development
  # database: db/development.sqlite3



test:
  <<: *default
  database: todo_test
  # database: db/test.sqlite3

production:
  <<: *default
  database: todo_production
  # database: db/production.sqlite3
